version: "4"

networks:
  router_revproxy_loadbalancer:

services:

  node2:
    image: pauloportfolio/webapp2:1.0
    restart: always
    build:
      context: ../../..
      dockerfile: ../dev/Dockerfile
    tty: true
    networks:
      - router_revproxy_loadbalancer