version: '3.4'

#DOCKER-COMPOSE COMMON VARIABLES [VARIAVEIS USADAS SOMENTE DENTRO DESTE DOCKER-COMPOSE FILE]
x-common-variables:
  &db-variables
    MYSQL_DATABASE: Users
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root

networks:
  db:
  router:

services:

  mysql:
    image: mysql:5.7.22
    #ports:         #DEBUG-PORT
    # - "8888:3306" #EXCLUSIVE PORT FOR DEBUG [PORTA EXCLUSIVA PARA DEBUG]
    hostname: mysql
    environment:
      *db-variables
    networks:
      - db
  
  webapp:
    build: webapp
    image: web-img
    #ports:         #TEST-PORT: EXCLUSIVE PORT FOR API TEST WITH HTTP-CLIENT[EX. POSTMAN]
    # - "8080:8080" #[PORTA EXCLUSIVA PARA TESTE DA API COM HTTP-CLIENTE[EX. POSTMAN]]
    hostname: web
    tty: true
    depends_on:
      - mysql
    environment:
      <<: *db-variables
      DB_PORT: tcp://mysql:3306
      DB_NOME_BANCO: Users
    networks:
      - db
      - router