version: "4"

networks:
  router_revproxy_loadbalancer:

services:

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx:/etc/nginx
    ports:
      - "80:3000"

# 02 SISTEMAS DE ESCALAGEM - DEPENDS_ON:
# A) Compose-Scale:
#    - somente usa 'node-1:8080" e escala no 'docker compose scale'
# B) Compose Services Duplicados:
#    - usa 'node-1:8080"/"node-2:8080" 02 Services vindos do Compose
    depends_on:
      - node-1  # WebApp1-Service (docker-scale OU node-service-duplicados)
      - node-2  # WebApp2-Service (node-service-duplicados)

    # LocalPort/EC2-Port[80]:NginxPortContainerService[3000] (server->listen Nginx.conf)
    networks:
      - router_revproxy_loadbalancer