version: '3.9'

networks:
  router:

services:
  router:
    build: ../nginx
    image: router-nginx-img
    ports:            #PORT:
      - "1111:8080"   #REQUEST ENTRY-POINT [PORTA DE ENTRADA DOS REQUESTS]
    hostname: router
    tty: true
    environment:
      - NGINX_PORT=8080
    depends_on:
      - webapp
    networks:
      - router