version: "4"

networks:
  router:

services:
  webapp:
    build:
      context: .. # Define o context[root] na pasta anterior, a pasta Docker
      dockerfile: ./Docker/DockerfileVaadin

    image: webapp-nginx-img
    ports: #TEST-PORT: EXCLUSIVE PORT FOR API TEST WITH HTTP-CLIENT[EX. POSTMAN]
      - "8080:8080" #[PORTA EXCLUSIVA PARA TESTE DA API COM HTTP-CLIENTE[EX. POSTMAN]]
    hostname: web
    tty: true
    #    depends_on:
    #      - mysql
#    networks:
#      - router